spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
springdoc:
  swagger-ui:
    path: /api-docs.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json


jwt:
  header: Authorization
  secret: ${JWT_KEY}
  #  token-validity-in-seconds: 86400
  token-validity-in-seconds: 1209600 # 테스트용 14일 유효기간

cloud:
  aws:
    s3:
      path:
        post : post
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:


